### ISSUE TITLE
Error when running: desktop-shell.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nakai-omer** [NVIDIA-ISAAC-ROS/isaac_ros_argus_camera#24]
Hello,

When trying to run this packages on a Jetson Xavier NX with Jetpack 5.1.1 we get the following error:
```
[component_container_mt-1] [INFO] [1688999329.344443872] [argus_stereo]: [NitrosContext] Loading extension: gxf/lib/libgxf_argus.so
[component_container_mt-1] [ERROR] [1688999329.388381422] [argus_stereo]: [NitrosContext] dlopen failed when opening "/home/nakai/development/nakai/packages/nakai-onboard/install/share/isaac_ros_gxf/gxf/lib/libgxf_argus.so": desktop-shell.so: cannot open shared object file: No such file or directory
[component_container_mt-1] [ERROR] [1688999329.388644049] [argus_stereo]: [NitrosNode] loadExtensions Error: GXF_FAILURE
[component_container_mt-1] [INFO] [1688999329.390370217] [argus_stereo]: [NitrosNode] Terminating the running application
[component_container_mt-1] [INFO] [1688999329.390515531] [argus_stereo]: [NitrosContext] Interrupting GXF...
[component_container_mt-1] 2023-07-10 17:28:49.390 ERROR gxf/std/program.cpp@475: Attempted interrupting when not running (state=0d).
[component_container_mt-1] 2023-07-10 17:28:49.390 ERROR gxf/core/runtime.cpp@1243: Graph interrupt failed with error: GXF_INVALID_EXECUTION_SEQUENCE

```

**Comment by jaiveersinghNV** [comment]
The path that `dlopen` is failing to open is set up in the [`CMakeLists.txt` of `isaac_ros_gxf`](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros/blob/main/isaac_ros_gxf/CMakeLists.txt#L32), a package under the Isaac ROS NITROS [repository](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros/).

Could you verify that the `isaac_ros_gxf` package has correctly been built on your machine? Additionally, can you check that the relevant [Argus library](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros/blob/main/isaac_ros_gxf/gxf/ext/lib/gxf_jetpack51/libgxf_argus.so) was correctly fetched from Git LFS?

Note that the Argus library has only been compiled for Jetson platforms, so using build products from an x86 environment will not work with Isaac ROS Argus Camera.
