### ISSUE TITLE
libargus compatibility

### ISSUE THREAD

**Issue by larganjohn** [NVIDIA-ISAAC-ROS/isaac_ros_argus_camera#25]
Hi,
If a camera supports libargus, does that also mean Isaac ROS Argus Camera supports it?
Do I need to configure the camera to be compatible with Isaac ROS Argus Camera if it's not listed in the [Reference Camera](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_argus_camera#reference-cameras)?
Thank you

**Comment by jaiveersinghNV** [comment]
Isaac ROS Argus Camera uses the NVIDIA [libargus](https://docs.nvidia.com/jetson/l4t-multimedia/group__LibargusAPI.html) under the hood. If a camera supports the libargus API, then it should also be supported by Isaac ROS Argus Camera.

The cameras listed in the Reference Cameras section you've linked are cameras that our team has verified with Isaac ROS Argus Camera specifically; that list is not a complete catalog of all supported cameras.
