### ISSUE TITLE
'colcon test --executor sequential' fails

### ISSUE THREAD

**Issue by D3-aavery** [NVIDIA-ISAAC-ROS/isaac_ros_argus_camera#30]
I'm observing the following error in the test log:

 [ERROR] [1696452358.054867679] [isaac_ros_test.argus_mono]: [NitrosContext] dlopen failed when opening "/workspaces/isaac_ros-dev/install/isaac_ros_gxf/share/isaac_ros_gxf/gxf/lib/libgxf_argus.so": libnvidia-kms.so.35.3.1: cannot open shared object file: No such file or directory
[component_container_mt-1] [ERROR] [1696452358.054933184] [isaac_ros_test.argus_mono]: [NitrosNode] loadExtensions Error: GXF_FAILURE

libnvidia-kms.so.35.3.1 exists in /usr/lib/aarch64-linux-gnu/tegra/ which is included in LD_LIBRARY_PATH.

**Comment by jaiveersinghNV** [comment]
Could you please try this again with the [latest release](https://nvidia-isaac-ros.github.io/releases/index#isaac-ros-2-0-0-october-18-2023)?

If you're still having problems, please provide details about the platform you're running on.
